{% set name = "telingo" %}
{% set version = "2.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/potassco/{{ name }}/archive/v{{ version }}.zip
  sha256: 973f9659ccfc006b0568e350b1cdc3c175840ff4cb3cc7ffcf648c2cbabe669d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - telingo = telingo:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - clingo >=5.5.0
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - telingo --version
    - pip check

about:
  home: https://potassco.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A solver for temporal logic programs.
  description: |
    Telingo is a solver for temporal programs. It leaverages clingo's input
    language and scripting cababilities to parse and solve programs with
    temporal formulas. As such the input of telingo is valid clingo input
    supporting all clingo language features like for example aggregates; only
    the way programs are grounded and solved is adjusted.
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}

extra:
  recipe-maintainers:
    - rkaminsk
